import { useState } from "react";
import { BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, ChevronsUpDown, FileText, Flower2, Home, Leaf, Menu, Search, ShieldCheck, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Section = "overview" | "schools" | "users" | "projects" | "project" | "measurements" | "calendar" | "photos" | "reports";
type Workspace = { workspace: { id: number; name: string; slug: string } };
type AppSidebarProps = { role: string; active: Section; onNavigate: (section: Section) => void; onCollapsedChange?: (collapsed: boolean) => void; workspaces?: Workspace[]; selectedWorkspaceId?: number; onWorkspaceChange?: (id?: number) => void };
const items: Array<{ id: Section; label: string; icon: typeof Home; roles: string[] }> = [
  { id: "overview", label: "Visão geral", icon: Home, roles: ["global_admin", "professor", "student"] },
  { id: "schools", label: "Escolas", icon: Flower2, roles: ["global_admin"] },
  { id: "users", label: "Usuários", icon: Users, roles: ["global_admin", "professor"] },
  { id: "projects", label: "Projetos", icon: Leaf, roles: ["global_admin", "professor", "student"] },
  { id: "measurements", label: "Medições", icon: BarChart3, roles: ["global_admin", "professor", "student"] },
  { id: "calendar", label: "Calendário", icon: CalendarDays, roles: ["global_admin", "professor", "student"] },
  { id: "photos", label: "Diário fotográfico", icon: FileText, roles: ["global_admin", "professor", "student"] },
  { id: "reports", label: "Relatórios", icon: BarChart3, roles: ["global_admin", "professor"] },
];

function WorkspaceSwitcher({ collapsed, workspaces, selectedWorkspaceId, onWorkspaceChange }: { collapsed: boolean; workspaces: Workspace[]; selectedWorkspaceId?: number; onWorkspaceChange?: (id?: number) => void }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const current = workspaces.find(item => item.workspace.id === selectedWorkspaceId)?.workspace;
  const filtered = workspaces.filter(item => `${item.workspace.name} ${item.workspace.slug}`.toLowerCase().includes(query.toLowerCase()));
  const choose = (id?: number) => { onWorkspaceChange?.(id); setOpen(false); setQuery(""); };
  return <div className="relative border-t border-white/10 p-3"><button className={cn("w-full rounded-2xl bg-white/10 text-left transition hover:bg-white/15", collapsed ? "p-2" : "p-3")} onClick={() => setOpen(value => !value)} aria-expanded={open} title={collapsed ? "Trocar workspace" : undefined}><div className={cn("flex items-center gap-2", collapsed && "justify-center")}><ChevronsUpDown className="h-4 w-4 shrink-0 text-[#d5ed8c]" />{!collapsed && <span className="min-w-0 flex-1"><span className="block text-[10px] font-semibold uppercase tracking-wider text-[#b9d1bd]">Workspace atual</span><span className="mt-0.5 block truncate text-xs font-medium text-white">{current?.name ?? "Administração geral"}</span></span>}</div></button>{open && <div className={cn("absolute bottom-16 z-50 rounded-2xl border border-[#d7e7d3] bg-white p-2 text-[#18352c] shadow-2xl", collapsed ? "left-2 w-64" : "left-3 right-3")}><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#78907d]" /><Input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar escola..." className="h-10 pl-9 text-sm" /></div><div className="mt-2 max-h-48 space-y-1 overflow-y-auto"><button onClick={() => choose(undefined)} className="flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-sm hover:bg-[#f0f7e9]"><span><span className="block font-medium">Administração geral</span><span className="text-xs text-[#78907d]">Visão master do sistema</span></span>{!selectedWorkspaceId && <Check className="h-4 w-4 text-[#4d7b58]" />}</button>{filtered.map(item => <button key={item.workspace.id} onClick={() => choose(item.workspace.id)} className="flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-sm hover:bg-[#f0f7e9]"><span><span className="block font-medium">{item.workspace.name}</span><span className="text-xs text-[#78907d]">/{item.workspace.slug}</span></span>{selectedWorkspaceId === item.workspace.id && <Check className="h-4 w-4 text-[#4d7b58]" />}</button>)}{!filtered.length && <p className="px-3 py-4 text-center text-xs text-[#78907d]">Nenhuma escola encontrada.</p>}</div></div>}</div>;
}

export function AppSidebar({ role, active, onNavigate, onCollapsedChange, workspaces = [], selectedWorkspaceId, onWorkspaceChange }: AppSidebarProps) {
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const visibleItems = items.filter(item => item.roles.includes(role));
  const navigate = (section: Section) => { onNavigate(section); setMobileOpen(false); };
  const content = <div className="flex h-full flex-col bg-[#173d32] text-white"><div className={cn("flex h-20 items-center border-b border-white/10 px-4", collapsed ? "justify-center" : "justify-between")}>{!collapsed && <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#d5ed8c] text-[#173d32]"><Leaf className="h-5 w-5" /></div><div><p className="font-semibold">Horta científica</p><p className="text-xs text-[#b9d1bd]">Painel UFNT</p></div></div>}{collapsed && <Leaf className="h-5 w-5 text-[#d5ed8c]" />}<button className="hidden rounded-lg p-2 text-[#b9d1bd] hover:bg-white/10 lg:block" onClick={() => { const next = !collapsed; setCollapsed(next); onCollapsedChange?.(next); }} aria-label={collapsed ? "Expandir menu" : "Recolher menu"}>{collapsed ? <ChevronRight className="h-5 w-5" /> : <ChevronLeft className="h-5 w-5" />}</button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{visibleItems.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => navigate(item.id)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition", active === item.id ? "bg-[#d5ed8c] font-medium text-[#173d32]" : "text-[#d8e6d9] hover:bg-white/10", collapsed && "justify-center px-2")} title={collapsed ? item.label : undefined}><Icon className="h-5 w-5 shrink-0" />{!collapsed && <span>{item.label}</span>}</button>; })}</nav><WorkspaceSwitcher collapsed={collapsed} workspaces={workspaces} selectedWorkspaceId={selectedWorkspaceId} onWorkspaceChange={onWorkspaceChange} />{!collapsed && <div className="border-t border-white/10 p-4"><div className="rounded-2xl bg-white/10 p-3 text-xs leading-5 text-[#d8e6d9]"><ShieldCheck className="mb-2 h-4 w-4 text-[#d5ed8c]" /><p>{role === "global_admin" ? "Acesso master a todas as escolas." : role === "professor" ? "Gestão da sua escola." : "Registros do seu projeto."}</p></div></div>}</div>;
  return <><button className="fixed left-4 top-4 z-40 rounded-xl bg-[#173d32] p-3 text-[#d5ed8c] shadow-lg lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Abrir menu"><Menu className="h-5 w-5" /></button><aside className={cn("fixed inset-y-0 left-0 z-30 hidden transition-all duration-200 lg:block", collapsed ? "w-[76px]" : "w-64")}>{content}</aside>{mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/40" onClick={() => setMobileOpen(false)} aria-label="Fechar menu" /><aside className="relative h-full w-72 shadow-2xl">{content}<button className="absolute right-3 top-5 rounded-lg p-2 text-[#b9d1bd] hover:bg-white/10" onClick={() => setMobileOpen(false)} aria-label="Fechar menu"><X className="h-5 w-5" /></button></aside></div>}</>;
}
export type { Section };
